### ISSUE TITLE
Dahua IP camera issue (Raspberry 4)

### ISSUE THREAD

**Issue by RusLis** [datarhei/restreamer#197]
Hello, as soon as I try to add link to a camera getting this error in logs:

[20-08-2020 18:17:01.969] [INFO ]      _       _             _           _
[20-08-2020 18:17:01.982] [INFO ]   __| | __ _| |_ __ _ _ __| |___   ___(_)
[20-08-2020 18:17:01.983] [INFO ]  / _  |/ _  | __/ _  |  __|  _  |/  _ | |
[20-08-2020 18:17:01.984] [INFO ] | (_| | (_| | || (_| | |  | | | |  __/| |
[20-08-2020 18:17:01.984] [INFO ] |_____|_____|_||_____|_|  |_| |_|____||_|
[20-08-2020 18:17:01.985] [INFO ]
[20-08-2020 18:17:01.985] [INFO ] Restreamer v0.6.6
[20-08-2020 18:17:01.986] [INFO ]
[20-08-2020 18:17:01.986] [INFO ] ENVIRONMENTS
[20-08-2020 18:17:01.987] [INFO ] More information in our Docs
[20-08-2020 18:17:01.987] [INFO ]
[20-08-2020 18:17:01.988] [INFO ] [                   ENV] RS_NODEJS_PORT = 3000 (using default) - Webserver port of application.
[20-08-2020 18:17:01.988] [INFO ] [                   ENV] RS_NODEJS_ENV = prod (using default) - Node.js Environment ('dev' or 'prod').
[20-08-2020 18:17:01.989] [INFO ] [                   ENV] RS_LOGLEVEL = 3 (using default) - Logging level (0=no logging, 1=ERROR, 2=WARN, 3=INFO, 4=DEBUG).
[20-08-2020 18:17:01.989] [INFO ] [                   ENV] RS_TIMEZONE = Europe/Berlin (using default) - Set the timezone. Accepts Olson timezone IDs.
[20-08-2020 18:17:01.990] [INFO ] [                   ENV] RS_SNAPSHOT_INTERVAL = 1m (using default) - Interval for new snapshots (in milliseconds, use suffix 's' for seconds, 'm' for minutes). Use a value of 0 to disable snapshots.
[20-08-2020 18:17:01.990] [INFO ] [                   ENV] RS_USERNAME = admin - Username for the backend.
[20-08-2020 18:17:01.991] [INFO ] [                   ENV] RS_PASSWORD = ****** - Password for the backend.
[20-08-2020 18:17:01.991] [INFO ] [                   ENV] RS_TOKEN =  (using default) - Token for pushing an RTMP stream.
[20-08-2020 18:17:01.991] [INFO ] [                   ENV] RS_DEBUG_HEAPDUMPS = false (using default) - Create heapdumps of application.
[20-08-2020 18:17:01.992] [INFO ] [                   ENV] RS_DEBUG = false (using default) - Enables debug reporting.
[20-08-2020 18:17:01.992] [INFO ] [                   ENV] RS_AUDIO = auto (using default) - Audio track handling: auto, none (remove audio), silence (force silence), aac (force AAC), mp3 (force MP3).
[20-08-2020 18:17:01.993] [INFO ] [                   ENV] RS_HTTPS = false (using default) - Enables HTTPS support for admin interface and embeddable player.
[20-08-2020 18:17:01.993] [INFO ] [                   ENV] RS_INPUTSTREAM =  (using default) - Automatically start pulling from this stream on a fresh Restreamer installation.
[20-08-2020 18:17:01.994] [INFO ] [                 NGINX] Starting ...
[20-08-2020 18:17:02.359] [INFO ] [                 NGINX] Successfully started
[20-08-2020 18:17:02.363] [INFO ] [        RestreamerData] Checking jsondb file...
[20-08-2020 18:17:02.427] [INFO ] [              publicIP] Retrieving public IP ...
[20-08-2020 18:17:02.436] [INFO ] [             Webserver] Starting ...
[20-08-2020 18:17:02.533] [INFO ] [             Webserver] Running on port 3000
[20-08-2020 18:17:02.566] [INFO ] [              publicIP] Found public IP: *********
[20-08-2020 18:17:02.659] [INFO ] [       checkForUpdates] Update checking succeeded. No updates available
[20-08-2020 18:19:10.377] [INFO ] [    repeatToLocalNginx] Start streaming
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /restreamer/src/classes/Restreamer.js:325:33
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:310:20)
    at Pipe.<anonymous> (net.js:672:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Restreamer@0.6.6 start: `node ./src/start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Restreamer@0.6.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-20T16_19_40_463Z-debug.log

> Restreamer@0.6.6 start /restreamer
> node ./src/start

[20-08-2020 18:19:44.055] [INFO ]      _       _             _           _
[20-08-2020 18:19:44.069] [INFO ]   __| | __ _| |_ __ _ _ __| |___   ___(_)
[20-08-2020 18:19:44.070] [INFO ]  / _  |/ _  | __/ _  |  __|  _  |/  _ | |
[20-08-2020 18:19:44.071] [INFO ] | (_| | (_| | || (_| | |  | | | |  __/| |
[20-08-2020 18:19:44.071] [INFO ] |_____|_____|_||_____|_|  |_| |_|____||_|
[20-08-2020 18:19:44.072] [INFO ]
[20-08-2020 18:19:44.072] [INFO ] Restreamer v0.6.6
[20-08-2020 18:19:44.072] [INFO ]
[20-08-2020 18:19:44.073] [INFO ] ENVIRONMENTS
[20-08-2020 18:19:44.073] [INFO ] More information in our Docs
[20-08-2020 18:19:44.074] [INFO ]
[20-08-2020 18:19:44.074] [INFO ] [                   ENV] RS_NODEJS_PORT = 3000 (using default) - Webserver port of application.
[20-08-2020 18:19:44.075] [INFO ] [                   ENV] RS_NODEJS_ENV = prod (using default) - Node.js Environment ('dev' or 'prod').
[20-08-2020 18:19:44.075] [INFO ] [                   ENV] RS_LOGLEVEL = 3 (using default) - Logging level (0=no logging, 1=ERROR, 2=WARN, 3=INFO, 4=DEBUG).
[20-08-2020 18:19:44.076] [INFO ] [                   ENV] RS_TIMEZONE = Europe/Berlin (using default) - Set the timezone. Accepts Olson timezone IDs.
[20-08-2020 18:19:44.076] [INFO ] [                   ENV] RS_SNAPSHOT_INTERVAL = 1m (using default) - Interval for new snapshots (in milliseconds, use suffix 's' for seconds, 'm' for minutes). Use a value of 0 to disable snapshots.
[20-08-2020 18:19:44.077] [INFO ] [                   ENV] RS_USERNAME = admin - Username for the backend.
[20-08-2020 18:19:44.077] [INFO ] [                   ENV] RS_PASSWORD = ****** - Password for the backend.
[20-08-2020 18:19:44.078] [INFO ] [                   ENV] RS_TOKEN =  (using default) - Token for pushing an RTMP stream.
[20-08-2020 18:19:44.078] [INFO ] [                   ENV] RS_DEBUG_HEAPDUMPS = false (using default) - Create heapdumps of application.
[20-08-2020 18:19:44.078] [INFO ] [                   ENV] RS_DEBUG = false (using default) - Enables debug reporting.
[20-08-2020 18:19:44.079] [INFO ] [                   ENV] RS_AUDIO = auto (using default) - Audio track handling: auto, none (remove audio), silence (force silence), aac (force AAC), mp3 (force MP3).
[20-08-2020 18:19:44.079] [INFO ] [                   ENV] RS_HTTPS = false (using default) - Enables HTTPS support for admin interface and embeddable player.
[20-08-2020 18:19:44.080] [INFO ] [                   ENV] RS_INPUTSTREAM =  (using default) - Automatically start pulling from this stream on a fresh Restreamer installation.
[20-08-2020 18:19:44.081] [INFO ] [                 NGINX] Starting ...
[20-08-2020 18:19:44.136] [ERROR] [                 NGINX] 30#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.36, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "192.168.0.71:8080"
[20-08-2020 18:19:44.395] [INFO ] [                 NGINX] Successfully started
[20-08-2020 18:19:44.397] [INFO ] [        RestreamerData] Checking jsondb file...
[20-08-2020 18:19:44.447] [INFO ] [              publicIP] Retrieving public IP ...
[20-08-2020 18:19:44.456] [INFO ] [             Webserver] Starting ...
[20-08-2020 18:19:44.553] [INFO ] [             Webserver] Running on port 3000
[20-08-2020 18:19:44.558] [INFO ] [    repeatToLocalNginx] Start streaming
[20-08-2020 18:19:44.583] [INFO ] [              publicIP] Found public IP: *******
[20-08-2020 18:19:44.687] [INFO ] [       checkForUpdates] Update checking succeeded. No updates available
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /restreamer/src/classes/Restreamer.js:325:33
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:310:20)
    at Pipe.<anonymous> (net.js:672:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Restreamer@0.6.6 start: `node ./src/start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Restreamer@0.6.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-20T16_20_14_646Z-debug.log

> Restreamer@0.6.6 start /restreamer
> node ./src/start

JSON:

**Comment by ioppermann** [comment]
@RusLis Yes, these special signs usually make problems on the command line where the shell might modify the command line that will effectively executed. Can you share how you originally wanted to start Restreamer? Maybe it can be fixed in Restreamer.
